name: slim
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.19.0
  - anyio=3.7.1
  - argon2-cffi-bindings=21.2.0
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.4
  - cryptography=41.0.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.4.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - faiss-gpu=1.7.4
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_resources=6.1.0
  - intel-openmp=2021.4.0
  - ipython_genutils=0.2.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.14
  - jupyter-lsp=2.2.0
  - jupyter_core=5.3.2
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyterlab_pygments=0.2.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libfaiss=1.7.4
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopus=1.3.1
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - notebook-shim=0.2.3
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - webencodings=0.5.1
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - altair==5.0.1
      - ansi2html==1.8.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - bbox-visualizer==0.1.0
      - bidict==0.22.1
      - black==23.7.0
      - boto3==1.34.13
      - botocore==1.34.13
      - cachetools==5.3.2
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==0.29.36
      - dash==2.11.1
      - dash-bootstrap-components==1.4.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.7.post1
      - dill==0.3.8
      - dnspython==2.4.2
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - eventlet==0.33.3
      - exceptiongroup==1.1.2
      - fastjsonschema==2.18.0
      - flake8==6.1.0
      - flask==2.2.5
      - flask-cors==4.0.0
      - flask-socketio==5.3.6
      - fonttools==4.42.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - greenlet==3.0.0
      - grpcio==1.59.2
      - h11==0.14.0
      - hdbscan==0.8.33
      - huggingface-hub==0.20.1
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - isort==5.12.0
      - itsdangerous==2.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpickle==3.0.2
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-events==0.7.0
      - jupyter-server==2.7.3
      - jupyter-server-proxy==4.1.0
      - jupyter-server-terminals==0.4.4
      - jupyter-ydoc==0.3.4
      - jupyterlab==4.0.6
      - jupyterlab-dash==0.1.0a3
      - jupyterlab-server==2.25.0
      - kiwisolver==1.4.4
      - littleutils==0.2.2
      - llvmlite==0.40.1
      - markdown==3.5.1
      - matplotlib==3.7.2
      - mccabe==0.7.0
      - multidict==6.0.4
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nbconvert==7.7.3
      - nest-asyncio==1.5.7
      - notebook==7.0.4
      - numba==0.57.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - ogb==1.3.6
      - opencv-python==4.8.0.76
      - outdated==0.2.2
      - overrides==7.4.0
      - parameterized==0.9.0
      - pathspec==0.11.2
      - pip==24.0
      - plotly==5.15.0
      - protobuf==4.23.4
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycodestyle==2.11.0
      - pyflakes==3.1.0
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - python-engineio==4.8.0
      - python-socketio==5.10.0
      - pytorch-transformers==1.2.0
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rpds-py==0.9.2
      - rsa==4.9
      - s3transfer==0.10.0
      - sacred==0.8.5
      - sacremoses==0.1.1
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.1
      - seaborn==0.12.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - simpervisor==1.0.0
      - simple-websocket==1.0.0
      - simplejson==3.19.1
      - slurmpy==0.0.8
      - smmap==5.0.1
      - soupsieve==2.4.1
      - tenacity==8.2.2
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - timm==0.9.12
      - tokenizers==0.15.0
      - toolz==0.12.0
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - tornado==6.3.3
      - tqdm==4.66.0
      - traitlets==5.9.0
      - transformers==4.36.2
      - umap-learn==0.5.3
      - uri-template==1.3.0
      - vega-datasets==0.9.0
      - wandb==0.16.1
      - wcwidth==0.2.6
      - webcolors==1.13
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - wilds==2.0.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - y-py==0.6.0
      - yacs==0.1.8
      - yarl==1.9.2
      - ypy-websocket==0.8.4